name: ocean-model-skill-assessor
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - cartopy
  - cf_xarray
  - extract_model
  # - jupyter
  # - jupyterlab
  - matplotlib-base
  # - numpy
  - ocean_data_gateway
  - ocean_model_skill_assessor
  - pip
  - scipy
  # - dask
  # - netcdf4
  - pandas
  - xarray
  - pip:
    - git+https://github.com/intake/intake
    - intake-erddap
    - intake-xarray
  #   # use these from github to include recent changes while packages are changing a lot
  #   # - git+git://github.com/axiom-data-science/extract_model#egg=extract_model
  #  - git+git://github.com/axiom-data-science/ocean-model-skill-assessor#egg=ocean-model-skill-assessor
