name: test_env_model_assessor
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - alphashape
  - cartopy
  - cf_pandas
  - cf_xarray
  - extract_model
  - intake
  # - intake-axds
  # - intake-erddap
  - matplotlib-base
  - numpy
  - pandas
  - scipy
  - tqdm
  - xarray
  ##############
  - pytest
  - pip:
    - intake-axds
    - intake-erddap
    - codecov
    - pytest-cov
    - coverage[toml]
