name: test_env_model_assessor
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - cartopy
  - cf_pandas
  - cf_xarray
  - extract_model
  - matplotlib-base
  - numpy
  - ocean_data_gateway
  - pandas
  - scipy
  - xarray
  ##############
  - pytest
  - pip:
    - git+https://github.com/intake/intake
    - intake-erddap
    - intake-xarray
    - codecov
    - pytest-cov
    - coverage[toml]
