name: omsa_docs
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - cartopy
   - matplotlib-base
   # - ipython
   # - jupyter
   # - jupyterlab
   - cf_xarray
   - extract_model
   - numpy
   - ocean_data_gateway
   - pandas
   - xarray
   # - xarray
   # These are needed for the docs themselves
   - jupytext
   - numpydoc
   - sphinx
   - sphinx-markdown-tables
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - recommonmark
   - pip:
     - git+https://github.com/intake/intake
     - intake-axds
     - intake-erddap
     - intake-xarray
     - cf-pandas
     - docrep<=0.2.7
     - furo
     - nbsphinx
     - jupyter_client
     - myst-nb
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
